export function SquiggleFilters() {
  return (
    <svg
      className="svg-filters"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      focusable="false"
    >
      <defs>
        <filter id="squiggle-1">
          <feTurbulence
            type="fractalNoise"
            baseFrequency="0.015"
            numOctaves={1}
            result="noise"
            seed={1}
          />
          <feDisplacementMap
            in="SourceGraphic"
            in2="noise"
            scale={4}
            xChannelSelector="R"
            yChannelSelector="G"
          />
        </filter>
        <filter id="squiggle-2">
          <feTurbulence
            type="fractalNoise"
            baseFrequency="0.015"
            numOctaves={1}
            result="noise"
            seed={15}
          />
          <feDisplacementMap
            in="SourceGraphic"
            in2="noise"
            scale={4}
            xChannelSelector="R"
            yChannelSelector="G"
          />
        </filter>
        <filter id="squiggle-3">
          <feTurbulence
            type="fractalNoise"
            baseFrequency="0.015"
            numOctaves={1}
            result="noise"
            seed={30}
          />
          <feDisplacementMap
            in="SourceGraphic"
            in2="noise"
            scale={4}
            xChannelSelector="R"
            yChannelSelector="G"
          />
        </filter>
        <filter id="squiggle-4">
          <feTurbulence
            type="fractalNoise"
            baseFrequency="0.015"
            numOctaves={1}
            result="noise"
            seed={45}
          />
          <feDisplacementMap
            in="SourceGraphic"
            in2="noise"
            scale={4}
            xChannelSelector="R"
            yChannelSelector="G"
          />
        </filter>
        <filter id="wrinkle-effect" x="-10%" y="-10%" width="120%" height="120%">
          <feTurbulence
            type="fractalNoise"
            baseFrequency="0.03"
            numOctaves={3}
            result="wrinkle-noise"
          />
          <feDisplacementMap
            in="SourceGraphic"
            in2="wrinkle-noise"
            scale={9}
            xChannelSelector="R"
            yChannelSelector="G"
          />
        </filter>
        <filter id="node-wrinkle-effect" x="-8%" y="-8%" width="116%" height="116%">
          <feTurbulence
            type="fractalNoise"
            baseFrequency="0.03"
            numOctaves={3}
            result="node-wrinkle-noise"
          />
          <feDisplacementMap
            in="SourceGraphic"
            in2="node-wrinkle-noise"
            scale={5}
            xChannelSelector="R"
            yChannelSelector="G"
          />
        </filter>
      </defs>
    </svg>
  );
}
